name: rssepisodeextractor # you probably want to 'snapcraft register <name>'
version: 'latest' # just for humans, typically '1.2+git' or '1.3.2'
summary: Get a list of links to the episodes of a podcast. # 79 char long summary
description: |
  Get a list of links to the episodes of a podcast which uses an rss feed with pagination.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  rssepisodeextractor:
    command: rssepisodeextractor
    plugs: [network]
  rssepisodeextractor-gtk:
    command: desktop-launch $SNAP/usr/bin/rssepisodeextractor-gtk
    plugs: [home, unity7, x11, desktop, network]

parts:
  rssepisodeextractor:
    plugin: python
    source: .
    python-packages:
      - feedparser
      - gi
    stage-packages:
      - python3
      - python3-gi
      - gir1.2-gtk-3.0
      - packagekit-gtk3-module
      - libdb5.3
    install: |
      cp bin/rssepisodeextractor $SNAPCRAFT_PART_INSTALL/usr/bin/
      cp bin/rssepisodeextractor-gtk $SNAPCRAFT_PART_INSTALL/usr/bin/
    after: [desktop-gtk3]
